# Homework05 - APIs

## 1.Use the BLS Data Finder 1.1 available here to import a BLS variable/field (using the BLS web API) of your choosing.

In [1]:
import requests
import pandas as pd
import numpy as np

In [4]:
base_url = 'https://api.bls.gov/publicAPI/v1/timeseries/data/' #API Location

In [6]:
series = {'id': 'LNS14000000',
          'name': 'Unemployment Rate'}

# Combine the base url and series id into a single string which is the API url with data. 
data_url = '{}{}'.format(base_url, series['id'])
print(data_url)

https://api.bls.gov/publicAPI/v1/timeseries/data/LNS14000000

In [7]:
r = requests.get(data_url).json()
print('Status: ' + r['status'])

r = r['Results']['series'][0]['data']

Status: REQUEST_SUCCEEDED

In [10]:
dates = ['{} {}'.format(i['periodName'], i['year']) for i in r]
index = pd.to_datetime(dates, format='%B %Y')
data = {series['id']: [float(i['value']) if i['value'] != '-' else np.nan for i in r]}

df = pd.DataFrame(index=index, data=data).iloc[::-1]
df

            LNS14000000
2024-01-01          3.7
2024-02-01          3.9
2024-03-01          3.9
2024-04-01          3.9
2024-05-01          3.9
2024-06-01          4.1
2024-07-01          4.2
2024-08-01          4.2
2024-09-01          4.1
2024-10-01          4.1
2024-11-01          4.2
2024-12-01          4.1
2025-01-01          4.0
2025-02-01          4.2
2025-03-01          4.2
2025-04-01          4.2
2025-05-01          4.3
2025-06-01          4.1
2025-07-01          4.3
2025-08-01          4.3
2025-09-01          4.4
2025-10-01          NaN
2025-11-01          4.5
2025-12-01          4.4
2026-01-01          4.3
2026-02-01          4.4
2026-03-01          4.3

## 2.Using the BLS web API, create your own custom function which can interact with the BLS web API. Your function should take three input parameters: name base_url_in, series_in, and title_in and return the relevant data series as a pd.DataFrame object. Test your function by replicating the GET request you sent above for #1.

In [20]:
#Step 1：Define the custom function, same step as the Q1
def get_bls_data(base_url_in, series_in, title_in):
    data_url = '{}{}'.format(base_url_in, series_in)
    
    r = requests.get(data_url).json()
    print('Status: ' + r['status'])
    
    r = r['Results']['series'][0]['data']
    
    dates = ['{} {}'.format(i['periodName'], i['year']) for i in r]
    index = pd.to_datetime(dates, format='%B %Y')
    data = {title_in: [float(i['value']) if i['value'] != '-' else np.nan for i in r]}
    
    df = pd.DataFrame(index=index, data=data).iloc[::-1]
    return df

In [21]:
# Step 2: Test the function by replicating #1
df = get_bls_data(base_url, 'LNS14000000', 'Unemployment Rate')
df

Status: REQUEST_SUCCEEDED

            Unemployment Rate
2024-01-01                3.7
2024-02-01                3.9
2024-03-01                3.9
2024-04-01                3.9
2024-05-01                3.9
2024-06-01                4.1
2024-07-01                4.2
2024-08-01                4.2
2024-09-01                4.1
2024-10-01                4.1
2024-11-01                4.2
2024-12-01                4.1
2025-01-01                4.0
2025-02-01                4.2
2025-03-01                4.2
2025-04-01                4.2
2025-05-01                4.3
2025-06-01                4.1
2025-07-01                4.3
2025-08-01                4.3
2025-09-01                4.4
2025-10-01                NaN
2025-11-01                4.5
2025-12-01                4.4
2026-01-01                4.3
2026-02-01                4.4
2026-03-01                4.3

## 3. Go to these three links: link1, link2, link3. On these webpages, you will see three different time series data sets. For each, you will also see both a Series Title and ID. Using the function you wrote to fetch data from the BLS web API, import these data sets into Python as three separate pd.Data.Frame objects.

In [24]:
#link 1
df1 = get_bls_data(base_url, 'APU0000709112', 'Milk (Fresh, Whole, per gallon)')
df1

Status: REQUEST_SUCCEEDED

            Milk (Fresh, Whole, per gallon)
2024-01-01                            3.958
2024-02-01                            3.940
2024-03-01                            3.893
2024-04-01                            3.868
2024-05-01                            3.864
2024-06-01                            3.956
2024-07-01                            3.983
2024-08-01                            4.044
2024-09-01                            4.021
2024-10-01                            4.041
2024-11-01                            4.138
2024-12-01                            4.101
2025-01-01                            4.025
2025-02-01                            4.026
2025-03-01                            4.050
2025-04-01                            4.074
2025-05-01                            4.022
2025-06-01                            4.029
2025-07-01                            4.162
2025-08-01                            4.171
2025-09-01                            4.129
2025-10-01                              NaN
2025-11-01                            3.997
2025-12-01                            4.047
2026-01-01                            4.100
2026-02-01                            4.026
2026-03-01                            4.067

In [25]:
#link 2
df2 = get_bls_data(base_url, 'APU000074714', 'Gasoline (Unleaded Regular, per gallon)')
df2

Status: REQUEST_SUCCEEDED

            Gasoline (Unleaded Regular, per gallon)
2024-01-01                                    3.221
2024-02-01                                    3.359
2024-03-01                                    3.581
2024-04-01                                    3.776
2024-05-01                                    3.755
2024-06-01                                    3.601
2024-07-01                                    3.622
2024-08-01                                    3.521
2024-09-01                                    3.344
2024-10-01                                    3.279
2024-11-01                                    3.181
2024-12-01                                    3.145
2025-01-01                                    3.211
2025-02-01                                    3.261
2025-03-01                                    3.232
2025-04-01                                    3.330
2025-05-01                                    3.306
2025-06-01                                    3.306
2025-07-01                                    3.285
2025-08-01                                    3.295
2025-09-01                                    3.339
2025-10-01                                    3.239
2025-11-01                                    3.228
2025-12-01                                    3.050
2026-01-01                                    2.961
2026-02-01                                    3.065
2026-03-01                                    3.843

In [26]:
#link 3
df3 = get_bls_data(base_url, 'APU0000708111', 'Eggs (Grade A, Large, per doz.)')
df3

Status: REQUEST_SUCCEEDED

            Eggs (Grade A, Large, per doz.)
2024-01-01                            2.522
2024-02-01                            2.996
2024-03-01                            2.992
2024-04-01                            2.864
2024-05-01                            2.699
2024-06-01                            2.715
2024-07-01                            3.080
2024-08-01                            3.204
2024-09-01                            3.821
2024-10-01                            3.370
2024-11-01                            3.649
2024-12-01                            4.146
2025-01-01                            4.953
2025-02-01                            5.897
2025-03-01                            6.227
2025-04-01                            5.122
2025-05-01                            4.548
2025-06-01                            3.775
2025-07-01                            3.599
2025-08-01                            3.587
2025-09-01                            3.488
2025-10-01                              NaN
2025-11-01                            2.860
2025-12-01                            2.712
2026-01-01                            2.577
2026-02-01                            2.500
2026-03-01                            2.348