# Homework05 - APIs

## 1.Use the BLS Data Finder 1.1 available here to import a BLS variable/field (using the BLS web API) of your choosing.

In [1]:
import requests
import pandas as pd
import numpy as np

In [4]:
base_url = 'https://api.bls.gov/publicAPI/v1/timeseries/data/' #API Location

In [6]:
series = {'id': 'LNS14000000',
          'name': 'Unemployment Rate'}

# Combine the base url and series id into a single string which is the API url with data. 
data_url = '{}{}'.format(base_url, series['id'])
print(data_url)

https://api.bls.gov/publicAPI/v1/timeseries/data/LNS14000000

In [7]:
r = requests.get(data_url).json()
print('Status: ' + r['status'])

r = r['Results']['series'][0]['data']

Status: REQUEST_SUCCEEDED

In [10]:
dates = ['{} {}'.format(i['periodName'], i['year']) for i in r]
index = pd.to_datetime(dates, format='%B %Y')
data = {series['id']: [float(i['value']) if i['value'] != '-' else np.nan for i in r]}

df = pd.DataFrame(index=index, data=data).iloc[::-1]
df

            LNS14000000
2024-01-01          3.7
2024-02-01          3.9
2024-03-01          3.9
2024-04-01          3.9
2024-05-01          3.9
2024-06-01          4.1
2024-07-01          4.2
2024-08-01          4.2
2024-09-01          4.1
2024-10-01          4.1
2024-11-01          4.2
2024-12-01          4.1
2025-01-01          4.0
2025-02-01          4.2
2025-03-01          4.2
2025-04-01          4.2
2025-05-01          4.3
2025-06-01          4.1
2025-07-01          4.3
2025-08-01          4.3
2025-09-01          4.4
2025-10-01          NaN
2025-11-01          4.5
2025-12-01          4.4
2026-01-01          4.3
2026-02-01          4.4
2026-03-01          4.3

## 2.Using the BLS web API, create your own custom function which can interact with the BLS web API. Your function should take three input parameters: name base_url_in, series_in, and title_in and return the relevant data series as a pd.DataFrame object. Test your function by replicating the GET request you sent above for #1.

In [20]:
#Step 1：Define the custom function, same step as the Q1
def get_bls_data(base_url_in, series_in, title_in):
    data_url = '{}{}'.format(base_url_in, series_in)
    
    r = requests.get(data_url).json()
    print('Status: ' + r['status'])
    
    r = r['Results']['series'][0]['data']
    
    dates = ['{} {}'.format(i['periodName'], i['year']) for i in r]
    index = pd.to_datetime(dates, format='%B %Y')
    data = {title_in: [float(i['value']) if i['value'] != '-' else np.nan for i in r]}
    
    df = pd.DataFrame(index=index, data=data).iloc[::-1]
    return df

In [21]:
# Step 2: Test the function by replicating #1
df = get_bls_data(base_url, 'LNS14000000', 'Unemployment Rate')
df

Status: REQUEST_SUCCEEDED

            Unemployment Rate
2024-01-01                3.7
2024-02-01                3.9
2024-03-01                3.9
2024-04-01                3.9
2024-05-01                3.9
2024-06-01                4.1
2024-07-01                4.2
2024-08-01                4.2
2024-09-01                4.1
2024-10-01                4.1
2024-11-01                4.2
2024-12-01                4.1
2025-01-01                4.0
2025-02-01                4.2
2025-03-01                4.2
2025-04-01                4.2
2025-05-01                4.3
2025-06-01                4.1
2025-07-01                4.3
2025-08-01                4.3
2025-09-01                4.4
2025-10-01                NaN
2025-11-01                4.5
2025-12-01                4.4
2026-01-01                4.3
2026-02-01                4.4
2026-03-01                4.3